queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=2"
      - check-success=build (stable)
      - check-success=CodeFactor
      - check-success=Rust project
    merge_conditions: []
    merge_method: squash

pull_request_rules:
  - name: automatic update of pull requests where more 5 commits behind
    conditions:
      - "#commits-behind>5"
    actions:
      update:
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
